# This is a basic workflow to help you get started with Actions

name: MyGitHubActions
env:
  APPLICATION_NAME : "my_flask"
  PACKAGE_NAME     : "flask_deploy_ver-${{github.sha}}"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push: 
    branches: 
      - master
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name:  print message
        run: 'echo hello world testing'
      - name: print ls
        run: ls -la
        
      - name: Execute few commands
        run: |
          echo "Hellow message"
          echo "Hellow Message2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
          
  my-deploy:
    runs-on: ubuntu-latest 
    needs: [build]
    steps:
      - name:  print message from deploy
        run: 'echo hello world deploy'

      - name : Print Deploy pacgake 
        run: echo "Deploy package name is ${{ env.APPLICATION_NAME }}"
